### PR TITLE
Fix favicon link

### PR DESCRIPTION
**Pull request by jsstrn**
Fixes issue #53 

I get an issue when running `npm run build:html`. It will replace the new favicon link with the older one.

### CODE REVIEW

**Comment by sayanee** [comment]
thanks @jsstrn Yes running `npm run build:html` will create the `html` files from `jade` file. 

You can see the code in `package.json` [L36](https://github.com/webuildsg/data/blob/82ac7e1890381b5835d4237c4a7d00e5955ab6a9/package.json#L36):

```js
"build:html": "gulp",
```

which in turn is calling the `gulpfile.js` to build the html files:

```js
gulp.task('default', function () {
  gulp.src('./views/index.jade').pipe(jade(jadeOptions)).pipe(gulp.dest('./'))
  gulp.src('./views/graphs/**/*.jade').pipe(jade(jadeOptions)).pipe(gulp.dest('./dataset'))
})
```

You can also try `npm start` to run the site locally and see if all the pages have the favicon.

Else I can merge it too as it looks good :+1:

**Comment by jsstrn** [comment]
@sayanee so that means I should be editing the `views/partials/head.jade` file instead of the `index.html` file directly, right?

**Comment by notthetup** [comment]
Yes. Edit the template and build the index.html.

**Comment by sayanee** [comment]
Both @jsstrn :smile: I updated the instructions in #53 

`index.html` is the homepage and `views/partials/head.jade` is the common head tag section of all the graph pages.

**Comment by notthetup** [comment]
So what is index.jade then?

**Comment by sayanee** [comment]
yuh just [explained above](https://github.com/webuildsg/data/pull/54#issuecomment-194628129)

**Comment by sayanee** [comment]
oops yes just `views/partials/head.jade` will do @jsstrn!  Then run `npm run build:html` and `git status` to check all the favicon links are correct and you are good to go :+1:

**Comment by notthetup** [comment]
OK. So am I right to say.. `index.jade` (which pulls in `head.jade`) is used to create `index.html` when you do `npm run build:html`.

So one should only ever be touching the `.jade` files manually. The `.html` files should be auto generated by the build command.

**Comment by sayanee** [comment]
:+1: :100: yes! 

Even if you touch the `html` files, the build process `npm run build:html` will over write it. So no problem at all!

**Comment by jsstrn** [comment]
@sayanee @notthetup thanks for clarifying. I've made the change and run the build. :+1:

**Comment by sayanee** [comment]
thanks @jsstrn for your contribution! You are now a collaborator on this repo 🤗 as this is an [OPEN Open source project](https://github.com/webuildsg/data/blob/gh-pages/CONTRIBUTING.md#open-open-source-project)

Have fun :tada:

**Comment by cheeaun** [comment]
:tada: :+1:

**Comment by jsstrn** [comment]
Thank you! :+1:

**Pull request merged**
