### PR TITLE
Add `for` to labels to make them clickable

### PR DESCRIPTION
**Pull request by winston**
Also remove extra "Language C" radio button.

:heart:

### CODE REVIEW

**Comment by sayanee** [comment]
thank you @winston for better html markup and yes, i have `C` duplicated :smile:

**Comment by sayanee** [comment]
In the spirit of [OPEN Open Source](https://github.com/webuildsg/data/blob/gh-pages/CONTRIBUTING.md#open-open-source-project) you can have commit access to this repository.

Thanks for your contribution @winston :heart_eyes:

**Comment by winston** [comment]
lol. Thanks! Although @cheeaun just overwrote my commit. 😂

**Comment by cheeaun** [comment]
@winston :smile: at least you found the duplicate "Language C".

**Comment by sayanee** [comment]
ooops yes :stuck_out_tongue_closed_eyes: 

the `for` attribute for the `label` tags not necessary anymore @cheeaun?

**Comment by winston** [comment]
Haha :heart: @cheeaun

Yup the "for" attr is not needed when you wrap the input in the label.


-- 
Cheers,
Winston

**Comment by cheeaun** [comment]
@winston @sayanee :+1:

**Pull request merged**
