### PR TITLE
Fix Event.srcElement not supported on Firefox

### PR DESCRIPTION
**Pull request by cheeaun**
- Also recode the `<label>` to wrap the `<input>` instead
- Also make sure the click works when click on `<label>`

### CODE REVIEW

**Comment by cheeaun** [comment]
:+1: All passed

**Comment by cheeaun** [comment]
@sayanee but, but `return` is not `goto` :weary:

**Comment by sayanee** [comment]
:+1: time to play with `jshint` config

**Comment by sayanee** [comment]
In the spirit of [OPEN Open Source](https://github.com/webuildsg/data/blob/gh-pages/CONTRIBUTING.md#open-open-source-project) you can have commit access to this repository.

Thanks for your contribution @cheeaun  :heart_eyes:

**Pull request merged**
